name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  zephyr-application:
    strategy:
      matrix:
        application: [ "app" ]
    uses: catie-aq/zephyr_workflows/.github/workflows/application.yml@main
    with:
      container: "ghcr.io/catie-aq/zephyr_docker:v0.26.18"
      application: {% raw %}${{ matrix.application }}{% endraw %}
      board: "{{cookiecutter.board}}"

    secrets:
      personal_access_token: {% raw %}${{ secrets.CI_6TRON_ZEPHYR_RO }}{% endraw %}
