name: "Test cookiecutter"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
                
jobs:
  test:
    strategy:
      matrix:
        templates: [ "core", "sensor", "shield", "workspace_application" ]
    runs-on: sonu-github-arc
    container:
      image: python:3.10
    steps:
    - uses: actions/checkout@v3
    - name: Install cookiecutter
      run: |
        pip install cookiecutter
    - name: Test cookiecutter
      run: |
        cd ${{ matrix.templates }}
        cookiecutter . --no-input --accept-hooks no
